name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "4835d996-2f36-4615-82b6-59f6963305b2"

[[kv_namespaces]]
binding = "kv"
id = "e35599d1dc154cb0843a9122af7f8743"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
orm_log = false
domain = ["chkseijuro.dev"]
admin = "admin@chkseijuro.dev"

[build]
command = "cd ../mail-vue && npm exec vite -- build --mode release"
